### ISSUE TITLE
Downloaded height map is solid black.  The preview looks correct.

### ISSUE THREAD

**Issue by delebash** [colkassad/terrain-rgb-demo-map#1]
This happens both on your live demo and this demo.

<img width="960" alt="mvfS5qs09U" src="https://user-images.githubusercontent.com/2220160/132104570-83a792a1-515f-446c-8eb7-ecc6745aa30c.png">

**Comment by delebash** [comment]
Never mind it was my problem. lol

**Comment by colkassad** [comment]
Yes, for anyone else that sees this, the preview is a standard RGB image, the downloaded image is single-band 16 bit (useful for heightmaps in stuff like the Unreal Engine but renders that way in many image viewers/editors).
