### ISSUE TITLE
Are you interested in any changes I make? Do you want pull requests?

### ISSUE THREAD

**Issue by delebash** [colkassad/terrain-rgb-demo-map#2]
Most of the stuff will be related to Unreal.  I added a function to calculate the Z height you need to use when importing to Unreal landscape.  Also added a config file to put Mapbox token and style url.  In addition, when you run npm start it launches your browser, so you don't have to do it manually.

I am using a copy of the project for my Unreal updates but I did fork your repo and can add any changes to that and send a pull request if you want.  My repos is at https://github.com/delebash/UnrealMapboxBridge.  I plan to add more to it as well as a way to auto update the landscape when you download a new heightmap.

**Comment by delebash** [comment]
Sample Unreal Landscape with 16bit png directly imported and Z height added.  You don't have to use World Machine.  Still needs some work with the edges and need to figure out how to get the correct landscape size when placing bounding box.
![zl2umAL0ZO](https://user-images.githubusercontent.com/2220160/132113492-05d9b9f4-efd9-474e-b0f5-7ede769fcadd.jpg)

**Comment by colkassad** [comment]
Yes, that would be wonderful! Feel free to post a pull request! Sorry for the late response.

**Comment by colkassad** [comment]
I actually would like to see your repo go off in that direction and I can keep mine as a starting point for poeple. I've noticed some others have started to fork mine as well. Would be happy to contribute your repo, I've been wanting to play around with Unreal again. Great work!
